name: XLSX to CSV Conversion on Pull Request


on:
  release:
    types: [published]
  pull_request_target:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - '!release-branch'
      - release*
      - master
      - 1.*
      - develop
      - MOSIP*

jobs:
  convert_xlsx_to_csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install xlsx2csv
      run: sudo apt-get install -y xlsx2csv  # Install the CLI tool

    - name: Create output directory
      run: mkdir -p mosip_master/csv  # Create the output directory

    - name: Convert all XLSX to CSV
      run: |
        for xlsx_file in mosip_master/xlsx/*.xlsx; do
          csv_file="mosip_master/csv/$(basename "${xlsx_file%.xlsx}.csv")"
          xlsx2csv "$xlsx_file" > "$csv_file"
          echo "Converted $xlsx_file to $csv_file"
        done
      
    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Commit message"
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
