name: XLSX to CSV Conversion on Pull Request

on:
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - '!release-branch'
      - release*
      - master
      - 1.*
      - develop
      - MOSIP*

jobs:
  convert_xlsx_to_csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Create output directory
      run: mkdir -p mosip_master/csv  # Create the output directory

    - name: xlsx To csv Action
      id: xlsx-to-csv-action
      uses: JoeSiu/xlsx-to-csv-action@1.0.0
      with:
        inputFile: 'mosip_master/xlsx/'
        outputDir: 'mosip_master/csv'
        outputFilename: 'sample-filtered'

    - name: Print Output
      id: output
      run: echo "${{ steps.xlsx-to-csv-action.outputs.outputFile }}"
      
    - name: Commit and push changes to a specific branch
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add mosip_master/csv/*.csv
        git commit -m "Convert XLSX files to CSV [skip ci]"
        git push origin HEAD:develop
